version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: churn_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/churn_analytics
      - REDIS_URL=redis://redis:6379/0
      - MLFLOW_TRACKING_URI=http://mlflow:5001
    depends_on:
      - postgres
      - redis
      - mlflow
    volumes:
      - ./backend:/app
      - ./data:/app/data

  mlflow:
    image: python:3.11-slim
    ports:
      - "5001:5001"
    environment:
      - BACKEND_STORE_URI=postgresql://postgres:postgres@postgres:5432/churn_analytics
      - ARTIFACT_ROOT=/mlflow/artifacts
    depends_on:
      - postgres
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    command: >
      bash -c "
        pip install mlflow psycopg2-binary &&
        mlflow server --backend-store-uri postgresql://postgres:postgres@postgres:5432/churn_analytics --default-artifact-root /mlflow/artifacts --host 0.0.0.0 --port 5001
      "

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  mlflow_artifacts:
